version: "3.8"

services:
  api:
    image: analysis-api
    ports:
      - "8080:80"
    links:
      - redis
  worker:
    image: analysis-worker
    command: celery -A app.celery worker -O fair -l DEBUG --concurrency=4
    environment:
      REFERENCE_FILEPATH: data/NC_000962.3.fasta
    links:
      - redis
  redis:
    image: redis