version: "3.8"

services:

  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    command: celery -A app.celery worker -O fair -l DEBUG --concurrency=4
    environment:
      REFERENCE_FILEPATH: data/NC_000962.3.fasta
    volumes:
    - ./uploads:/uploads:ro
    links:
      - redis

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "8080:80"
    links:
      - redis

  redis:
    image: redis