version: "3.8"

services:
  api:
    image: analysis-api
    ports:
      - "8080:80"
    links:
      - redis
  worker:
    image: analysis-worker
    command: celery -A app.celery worker -O fair -l DEBUG --concurrency=4
    links:
      - redis
  redis:
    image: redis