from analyses.predictor import PredictorTaskManager
from analyses.kmer_index import KmerIndexTaskManager
from analyses.distance import DistanceTaskManager
from analyses.cluster import ClusterTaskManager
from analyses.mappings import MappingsManager
