apiVersion: v1
kind: Service
metadata:
  name: mykrobe-atlas-bigsi-service
  labels:
    app: mykrobe-atlas-bigsi
spec:
  type: NodePort
  ports:
  - port: 8001
    targetPort: 8001     
  selector:
    app: mykrobe-atlas-bigsi