apiVersion: v1
data:
  BIGSI_CONFIG: "/etc/bigsi/conf/config.yaml"
kind: ConfigMap
metadata:
  name: mykrobe-atlas-bigsi-env
---
apiVersion: v1
data:
  config.yaml: |-
    h: 1
    k: 31
    m: 28000000
    nproc: 1
    storage-engine: berkeleydb
    storage-config:
      filename: /data/test-bigsi-bdb
      flag: "c" ## Change to 'r' for read-only access
kind: ConfigMap
metadata:
  name: mykrobe-atlas-bigsi-config
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mykrobe-atlas-bigsi-deployment
  labels:
    app: mykrobe-atlas-bigsi  
    tier: front    
spec:
  selector:
    matchLabels:
      app: mykrobe-atlas-bigsi
  template:
    metadata:
      labels:
        app: mykrobe-atlas-bigsi  
    spec:    
      volumes:
        - name: pv-storage-for-mykrobe-atlas-bigsi
          persistentVolumeClaim:
           claimName: pv-claim-for-mykrobe-atlas-bigsi  
        - name: configmap-volume
          configMap:
            name: mykrobe-atlas-bigsi-config              
      containers:
      - name: mykrobe-atlas-bigsi
        image: phelimb/bigsi:v0.3.5
        command: ["/bin/sh"]
        args: ["-c","uwsgi --enable-threads --http :80 --wsgi-file bigsi/__main__.py --callable __hug_wsgi__ --processes=4 --buffer-size=32768 --harakiri=300000"]
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: "/data/"
            name: pv-storage-for-mykrobe-atlas-bigsi
          - mountPath: /etc/bigsi/conf/
            name: configmap-volume  
        envFrom:
          - configMapRef:
              name: mykrobe-atlas-bigsi-env                         
---
apiVersion: v1
kind: Service
metadata:
  name: mykrobe-atlas-bigsi-service
  labels:
    app: mykrobe-atlas-bigsi
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: mykrobe-atlas-bigsi



