kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-claim-for-mykrobe-atlas-bigsi
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi