apiVersion: v1
kind: Service
metadata:
  name: mykrobe-atlas-bigsi-aggregator-nginx-service
  labels:
    app: mykrobe-atlas-bigsi-aggregator-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80  
    name: http  
  selector:
    app: mykrobe-atlas-bigsi-aggregator-nginx
