apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mykrobe-atlas-analysis-api
  labels:
    app: mykrobe-atlas-analysis-api  
spec:
  selector:
    matchLabels:
      app: mykrobe-atlas-analysis-api
  template:
    metadata:
      labels:
        app: mykrobe-atlas-analysis-api  
    spec:    
      volumes:
        - name: pv-storage-for-atlas
          persistentVolumeClaim:
           claimName: pv-claim-for-atlas           
      imagePullSecrets:
        - name: private-registry-key
      containers:
      - name: mykrobe-atlas-analysis
        image: phelimb/mykrobe-atlas-analysis-api:a12fa4f
        command: ["/bin/sh"]
        args: ["-c","uwsgi --http :80  --harakiri 300  --buffer-size=65535  -w wsgi:app"]
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: "/data/"
            name: pv-storage-for-atlas          
        envFrom:
          - configMapRef:
              name: env            
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mykrobe-atlas-analysis-worker
  labels:
    app: mykrobe-atlas-analysis-worker
spec:
  selector:
    matchLabels:
      app: mykrobe-atlas-analysis-worker
  template:
    metadata:
      labels:
        app: mykrobe-atlas-analysis-worker
    spec:      
      volumes:
        - name: pv-storage-for-atlas
          persistentVolumeClaim:
           claimName: pv-claim-for-atlas     
      containers:
      - name: mykrobe-atlas-analysis
        image: phelimb/mykrobe-atlas-analysis-api:a12fa4f
        command: ["celery"]
        args: ["-A", "app.celery", "worker", "-O", "fair" ,"-l","info","--concurrency=1",]          
        volumeMounts:
          - mountPath: "/data/"
            name: pv-storage-for-atlas
        envFrom:
          - configMapRef:
              name: env           
---
apiVersion: v1
kind: Service
metadata:
  name: mykrobe-atlas-analysis-api
  labels:
    app: mykrobe-atlas-analysis-api
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80     
  selector:
    app: mykrobe-atlas-analysis-api
