kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume-for-atlas
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data" ## Make sure this path exists on the local machine, if you're using minikube this will be in the VM, not local disk.