apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: analysis-worker
  labels:
    app: analysis-worker
spec:
  selector:
    matchLabels:
      app: analysis-worker
  template:
    metadata:
      labels:
        app: analysis-worker
    spec:       
      containers:
      - name: analysis-worker
        image: phelimb/mykrobe-atlas-analysis-api:e14eb8ebd7
        imagePullPolicy: Never        
        command: ["celery"]
        args: ["-A", "app.celery", "worker"]
