#######
# EHK #
#######
variables:
  #CLUSTER: "argent"
  KUBECONFIG: ${CI_PROJECT_DIR}/osk/argent.yml

#dev-ehk:
#  stage: dev
#  image: onedata/oneclient:18.02.3
#  variables:
#    hostname: 1000genomeop.embl.tk
#    token: MDAxNWxvY2F00aW9uIG9uZXpvbmUKMDAzMGlkZW500aWZpZXIgNmRjMDc00MWI1ZDA3M2EzMjA2OTgzMjMxZmMyNTk3OWUKMDAxYWNpZCB00aW1lIDwgMTYwMTg5Mjg4NwowMDJmc2lnbmF00dXJlIKwBS87mI1OxXdUxMD006YYwD35q6aJO8MvcyShxzzhs8Cg
#    mountpnt: ${CI_PROJECT_DIR}/1000g
#  script:
#    - mkdir -p ${mountpnt}
#    - oneclient -H ${hostname} -t ${token} ${mountpnt}
#    - dir -la ${mountpnt}
##    - ${CI_PROJECT_DIR}/onedata.sh 1000genomeop.embl.tk MDAxNWxvY2F00aW9uIG9uZXpvbmUKMDAzMGlkZW500aWZpZXIgNmRjMDc00MWI1ZDA3M2EzMjA2OTgzMjMxZmMyNTk3OWUKMDAxYWNpZCB00aW1lIDwgMTYwMTg5Mjg4NwowMDJmc2lnbmF00dXJlIKwBS87mI1OxXdUxMD006YYwD35q6aJO8MvcyShxzzhs8Cg ${CI_PROJECT_DIR}/1000g | tee ${ARTIFACT_DIR}/onedata.log
#  artifacts:
#    when: always
#    name: "$CI_COMMIT_REF_NAME-$CI_JOB_STAGE-$CI_JOB_NAME"
#    paths:
#      - ${ARTIFACT_DIR}

build-ehk:
  stage: build
  image: google/cloud-sdk
  script:
    - ${CI_PROJECT_DIR}/check.k8s.sh | tee ${ARTIFACT_DIR}/check.k8s.log
  artifacts:
    when: always
    name: "$CI_COMMIT_REF_NAME-$CI_JOB_STAGE-$CI_JOB_NAME"
    paths:
      - ${ARTIFACT_DIR}

deploy-ehk:
  stage: deploy
  image: google/cloud-sdk
  script:
    - ${CI_PROJECT_DIR}/apply.sh
  artifacts:
    when: always
#    untracked: true
    name: "$CI_COMMIT_REF_NAME-$CI_JOB_STAGE-$CI_JOB_NAME"
    paths:
      - ${ARTIFACT_DIR}
  dependencies:
     - build-ehk
  environment:
    name: Embassy
    url: https://extcloud05.ebi.ac.uk/
    on_stop: erase-ehk

erase-ehk:
  stage: test
  image: google/cloud-sdk
  script:
    - ${CI_PROJECT_DIR}/delete.sh
  when: manual
  artifacts:
    when: always
    name: "$CI_COMMIT_REF_NAME-$CI_JOB_STAGE-$CI_JOB_NAME"
    paths:
      - ${ARTIFACT_DIR}
  dependencies:
    - build-ehk
  environment:
    name: Embassy
    action: stop